#!/bin/bash

# Setup Git Pre-Commit Hook for Database Backup

echo "=== Setup Git Pre-Commit Hook for Database Backup ==="
echo ""

# Detect project directories
WORKSPACE="/home/sysop/.openclaw/workspace"
BACKEND_DIR="$WORKSPACE/apistreamhub-fastapi"
FRONTEND_DIR="$WORKSPACE/streamhub-nextjs"

# Function to install pre-commit hook
install_hook() {
    local PROJECT_DIR="$1"
    local PROJECT_NAME="$2"

    if [ ! -d "$PROJECT_DIR/.git" ]; then
        echo "⚠️  $PROJECT_NAME: No git repository found, skipping..."
        return
    fi

    echo "📦 Installing pre-commit hook for $PROJECT_NAME..."

    # Create hooks directory
    HOOKS_DIR="$PROJECT_DIR/.git/hooks"
    mkdir -p "$HOOKS_DIR"

    # Copy pre-commit hook
    cat > "$HOOKS_DIR/pre-commit" << 'EOF'
#!/bin/bash

# Git Pre-Commit Hook for PostgreSQL Backup
set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

BACKUP_DIR="$(git rev-parse --show-toplevel)/backups/database"
DATE=$(date +%Y%m%d_%H%M%S)
CONTAINER_NAME="apistreamhub-db"
DB_NAME="apistreamhub"
DB_USER="postgres"

mkdir -p "$BACKUP_DIR"

BRANCH_NAME=$(git branch --show-current)

echo -e "${YELLOW}🔄 Pre-Commit: Backing up database...${NC}"

docker exec $CONTAINER_NAME pg_dump \
  -U $DB_USER \
  --clean \
  --if-exists \
  $DB_NAME 2>/dev/null | \
  gzip > "$BACKUP_DIR/${DB_NAME}_${BRANCH_NAME}_${DATE}.sql.gz" || {
    echo "⚠️  Database backup failed (continuing with commit)"
    exit 0
}

echo -e "${GREEN}✓ Backup: ${DB_NAME}_${BRANCH_NAME}_${DATE}.sql.gz${NC}"

# Keep only last 10 backups
find "$BACKUP_DIR" -name "*.sql.gz" -type f | sort -r | tail -n +11 | xargs rm -f 2>/dev/null || true

exit 0
EOF

    # Make executable
    chmod +x "$HOOKS_DIR/pre-commit"

    # Create .gitignore for backups (optional, to not commit backups)
    if [ ! -f "$PROJECT_DIR/.gitignore" ] || ! grep -q "backups/database" "$PROJECT_DIR/.gitignore"; then
        echo "" >> "$PROJECT_DIR/.gitignore"
        echo "# Database backups (auto-generated by pre-commit hook)" >> "$PROJECT_DIR/.gitignore"
        echo "backups/database/" >> "$PROJECT_DIR/.gitignore"
    fi

    echo -e "${GREEN}✓ Pre-commit hook installed for $PROJECT_NAME${NC}"
    echo ""
}

# Install hooks for both projects
install_hook "$BACKEND_DIR" "Backend (apistreamhub-fastapi)"
install_hook "$FRONTEND_DIR" "Frontend (streamhub-nextjs)"

echo "=== Setup Complete ==="
echo ""
echo "Pre-commit hooks are now active!"
echo ""
echo "What happens now:"
echo "  1. Every 'git commit' will trigger database backup"
echo "  2. Backups are saved in: backups/database/"
echo "  3. Only last 10 backups are kept per project"
echo "  4. Backups are NOT committed to git (in .gitignore)"
echo ""
echo "Example:"
echo "  $ git commit -m 'fix: update API endpoint'"
echo "  → Database backup runs automatically"
echo "  → Backup saved: apistreamhub_master_20260301_070000.sql.gz"
echo "  → Commit proceeds"
echo ""
echo "✅ Ready to use!"
